function MLSC = MLSC_init(n,m1,m2)
MLSC = struct('n',n,'m1',m1,'m2',m2,...
    'D1',[],...
    'D2',[],...
    'D_eff',[],...
    'l1',[],...
    's2',[],...
    'sig_norm',[],...
    'dict_type',[]...
    );
end